---
title: "result"
author: "Dingxian Cao"
date: "April 5, 2016"
output: 
  html_document: 
    toc: yes
---

## 1.data process  

```{r}
source("clean2.R")
```

## 2.classification-SVM 

### 2.1 Use lag items of DD as inputs  

```{r}
source("classification_auto.R")
```  

### 2.2 Use mixed lag items as inputs

```{r}
source("classification_mixed.R")
```  

## 3. Regression-SVM  

### 3.1 Use lag items of DD as inputs  

```{r} 
source("svmRegression_auto.R")
```  


### 3.2 Use mixed lag items as inputs  

```{r}  
source("svmRegression_mixed.R")
```


## 4. KPCA+RegressionSVM  

```{r}  
source("Gaussionkpca+svmR.R")
```




## 5. Tune 


```{r}  
source("tune_svm_auto.R")  
source("tune_svm_auto.R")  
``` 

## 6. svmRegression_mixed vs classification

```{r}
source("svmRegression_mixed.R")
new<-mixRollSVMR(lag_num = 5,"radial",insampletest = FALSE,roll_num = 5,corlags=4)  
sign(diff(new))
sign(diff(cl.test$DD))
error<- ifelse(sign(diff(new))== sign(diff(cl.test$DD)),0,1)
(sum(error,na.rm = T)+1)/(length(error[-1])+1)
```






